"""Report generation service"""
from datetime import datetime
from typing import List
from uuid import UUID

from sqlalchemy.orm import Session

from app.models import Vendor, VendorScore, Alert


def generate_vendor_report_markdown(vendor: Vendor, score: VendorScore, alerts: List[Alert]) -> str:
    """
    Generate a vendor risk report in Markdown format.

    Framed against GDPR Art. 28/33, NIST SP 800-53 SA-9, SOX 404.
    """
    report = f"""# Vendor Risk Assessment Report

**Vendor:** {vendor.name}
**Type:** {vendor.type.value}
**Report Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

## Executive Summary

**Risk Tier:** {score.tier.value} ({score.status_color.value})
**Composite Score:** {score.composite_score:.1f}/100
**Last Assessed:** {vendor.last_assessed_at.strftime('%Y-%m-%d') if vendor.last_assessed_at else 'Never'}

### Risk Rationale
{score.rationale or 'No rationale available.'}

---

## Risk Score Breakdown

| Factor | Score | Weight |
|--------|-------|--------|
| Breach History | {score.breach_subscore:.1f} | 40% |
| Data Access Scope | {score.access_subscore:.1f} | 25% |
| Compliance Maturity | {score.compliance_subscore:.1f} | 20% |
| Financial Stability | {score.financial_subscore:.1f} | 15% |

**Anomaly Types:** {', '.join(score.anomaly_types) if score.anomaly_types else 'None'}

---

## Contract Information

- **Contract Period:** {vendor.contract_start.strftime('%Y-%m-%d') if vendor.contract_start else 'N/A'} to {vendor.contract_end.strftime('%Y-%m-%d') if vendor.contract_end else 'N/A'}
- **Status:** {vendor.contract_status if vendor.contract_status else 'N/A'}
- **Annual Spend:** {"${:,.2f}".format(vendor.annual_spend) if vendor.annual_spend else 'N/A'}

---

## Data Access Scope

"""

    if vendor.data_access_scope:
        scope = vendor.data_access_scope
        report += f"""- **PII Access:** {'Yes' if scope.get('pii') else 'No'}
- **Financial Data Access:** {'Yes' if scope.get('financial') else 'No'}
- **Systems:** {', '.join(scope.get('systems', [])) or 'None specified'}
- **Notes:** {scope.get('scope_notes', 'None')}
"""
    else:
        report += "No data access scope defined.\n"

    report += "\n---\n\n## Certifications\n\n"

    if vendor.certifications:
        report += "| Type | Status | Issued | Expires |\n|------|--------|--------|----------|\n"
        for cert in vendor.certifications:
            report += f"| {cert.get('type', 'N/A')} | {cert.get('status', 'N/A')} | {cert.get('issued_date', 'N/A')} | {cert.get('expiry_date', 'N/A')} |\n"
    else:
        report += "No certifications on record.\n"

    report += "\n---\n\n## Breach History\n\n"

    if vendor.breach_history:
        for breach in vendor.breach_history:
            report += f"""### {breach.get('date', 'Unknown Date')}
- **Severity:** {breach.get('severity', 'Unknown')}
- **Source:** {breach.get('source', 'Unknown')}
- **Description:** {breach.get('description', 'No description')}
- **Resolved:** {'Yes' if breach.get('resolved') else 'No'}

"""
    else:
        report += "No breach history recorded.\n"

    report += "\n---\n\n## Active Alerts\n\n"

    if alerts:
        for alert in alerts:
            report += f"- **[{alert.severity.value}]** {alert.message} (Created: {alert.created_at.strftime('%Y-%m-%d')})\n"
    else:
        report += "No active alerts.\n"

    report += f"""
---

## Compliance Framework Mapping

### GDPR Article 28/33 (Third-Party Processor Requirements)
- Data processing agreement: {'In place' if vendor.contract_status.value == 'active' else 'Missing/Expired'}
- Breach notification capability: {('Adequate (72h SLA)' if vendor.breach_history else 'Not tested')}

### NIST SP 800-53 SA-9 (External System Services)
- Security assessment: {'Current' if vendor.last_assessed_at else 'Overdue'}
- Continuous monitoring: {'Active' if score.tier != 'CLEAR' else 'Standard'}

### SOX 404 (Internal Controls)
- Vendor risk assessment: Documented in this report
- Control attestation: {'SOC 2 Type II' if any(c.get('type') == 'SOC2_TYPE2' for c in vendor.certifications) else 'Not available'}

---

*This report was generated by VendorSentry AI-Powered Risk Intelligence.*
"""

    return report


def generate_portfolio_report_markdown(db: Session) -> str:
    """Generate a portfolio-wide risk report"""
    vendors = db.query(Vendor).filter(Vendor.archived_at.is_(None)).all()

    report = f"""# Portfolio Risk Assessment Report

**Report Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
**Total Active Vendors:** {len(vendors)}

---

## Portfolio Risk Distribution

"""

    # Count by tier
    tier_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "CLEAR": 0}

    for vendor in vendors:
        latest_score = db.query(VendorScore).filter(
            VendorScore.vendor_id == vendor.id
        ).order_by(VendorScore.computed_at.desc()).first()

        if latest_score:
            tier_counts[latest_score.tier.value] += 1
        else:
            tier_counts["CLEAR"] += 1

    report += "| Risk Tier | Count | Percentage |\n|-----------|-------|------------|\n"
    for tier, count in tier_counts.items():
        pct = (count / len(vendors) * 100) if vendors else 0
        report += f"| {tier} | {count} | {pct:.1f}% |\n"

    report += "\n---\n\n## Recommendations\n\n"

    if tier_counts["CRITICAL"] > 0:
        report += f"- **URGENT:** {tier_counts['CRITICAL']} vendor(s) at CRITICAL risk require immediate review\n"
    if tier_counts["HIGH"] > 0:
        report += f"- {tier_counts['HIGH']} vendor(s) at HIGH risk should be reassessed within 30 days\n"

    report += """
---

*This report provides an executive overview. Individual vendor reports available on request.*
"""

    return report
