"""Add source_vendor_id and source_risk_score

Revision ID: f20729af1e7b
Revises: c09a265ec76a
Create Date: 2026-06-21 14:01:45.451190+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f20729af1e7b'
down_revision: Union[str, None] = 'c09a265ec76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ground_truth', sa.Column('source_vendor_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_ground_truth_source_vendor_id'), 'ground_truth', ['source_vendor_id'], unique=False)
    op.add_column('vendors', sa.Column('source_vendor_id', sa.String(length=255), nullable=True))
    op.add_column('vendors', sa.Column('source_risk_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vendors_source_vendor_id'), 'vendors', ['source_vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_source_vendor_id'), table_name='vendors')
    op.drop_column('vendors', 'source_risk_score')
    op.drop_column('vendors', 'source_vendor_id')
    op.drop_index(op.f('ix_ground_truth_source_vendor_id'), table_name='ground_truth')
    op.drop_column('ground_truth', 'source_vendor_id')
    # ### end Alembic commands ###
